language: generic 
sudo: required
services:
 - docker

before_install: 
  - docker build -t cruzlll/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true cruzlll/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-798997174704"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


