language: generic 
sudo: required
services:
 - docker

before_install: 
  - docker build -t cruzlll/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true cruzlll/docker-react npm run test